name: GitHub Actions Demo

on:
  push:
    branches: [ master ]
  pull_requiest:
    branches: [ master ]

jobs:
  integration-tests:

    needs: unit-tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
        run: mvn -B -clean package
