name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
#      - name: Build with Maven
#        run: mvn clean install -B
      - name: Unit_tests
        run: mvn test -f pom.xml
#      - name: Integration_tests
#        run: mvn integration-test -f pom.xml
#        run: mvn clean package
#        run: mvn --batch-mode --update-snapshots package