name: Module and Integration tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build with Maven
        run: mvn clean install -B
  unit:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Unit_tests
        run: mvn -f pom.xml test

  integration:
#    needs: unit
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Integration_tests
        run: mvn -f pom.xml verify -Pintegration-tests

  cypress-run:
#    needs: integration
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

#      - name: Start backend server
#        run: node server.js
#
#      - name: Wait for backend server to be ready
#        run: wait-on http://localhost:8080

      - name: start frontend server
        uses: cypress-io/github-action@v2
        with:
          start: npm start # Запускает ваше приложение
          wait-on: 'http://localhost:3000' # URL вашего приложения
          wait-on-timeout: 120 # Время ожидания загрузки вашего приложения

      - name: Run e2e tests
        run: npx cypress open

#        working-directory: ./documents-app
#        run: mvn clean package
#        run: mvn --batch-mode --update-snapshots package