name: Module and Integration tests

on: [push]

jobs:
#  BUILD
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build with Maven
        run: mvn clean install -B

#RUN UNIT TESTS
  UNIT_TESTS:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Unit_tests
        run: mvn -f pom.xml test -Dtest=**/documents/jpa/**/*.java


#RUN INTEGRATION TESTS
  INTEGRATION_TESTS:
    needs: UNIT_TESTS
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Maven install
        run: mvn install

      - name: Integration_tests
        run: mvn -f pom.xml verify


#RUN E2E TESTS
  E2E_TESTS:
    needs: INTEGRATION_TESTS
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install docker compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and Run Docker Compose
        run: docker-compose up -d

      - name: Install dependencies
        working-directory: my-admin
        run: |
          npm install
          npm start &

      - name: Install Cypress
        run: npm install cypress

      - name: cypress run
        uses: cypress-io/github-action@v5
